version: '3.8'
services:
  rabbitmq-litigation:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=felix
      - RABBITMQ_DEFAULT_PASS=56725672
    networks:
      - mynetwork

networks:
  mynetwork:
