version: '3.8'
services:
  rabbitmq-authentication:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=felix
      - RABBITMQ_DEFAULT_PASS=56725672
    networks:
      - mynetwork

networks:
  mynetwork:
