# Use the rabbitmq:3-management image as the base
FROM rabbitmq:3-management

# Expose ports for RabbitMQ and the management interface
EXPOSE 5673 15672

# Set environment variables for the default RabbitMQ user and password
ENV RABBITMQ_DEFAULT_USER=felix
ENV RABBITMQ_DEFAULT_PASS=56725672
